spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simpleweb
    username: postgres
    password:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
